### ISSUE TITLE
Starred list is centered, while other lists are left-aligned

### ISSUE THREAD

**Issue by yagnyaPatel** [shouryan01/google-tasks-desktop#7]
<img width="713" alt="image" src="https://github.com/user-attachments/assets/6ed8e79d-ae97-4b17-a2d6-ead03e088b73">
<img width="728" alt="image" src="https://github.com/user-attachments/assets/f1970143-94df-40c8-8d07-230b0ebb7a7c">

**Comment by shouryan01** [comment]
This is by design from Google, it is to show that this list is an aggregate from other lists. I cannot change this.

**Comment by shouryan01** [comment]
This is by design from Google, it is to show that this list is an aggregate from other lists. I cannot change this.
